### ISSUE TITLE
[Not a bug] [Info] Dolphin integration

### ISSUE THREAD

**Issue by pizzadude** [flathub/io.github.peazip.PeaZip#2]
Hi, thanks for making a Peazip flatpak.

For Dolphin file manager (kde) integration,
put this https://gist.github.com/pizzadude/b4e8aacb52f5a7d52d70f1b4df79137c
in ~/.local/share/kservices5/ServiceMenus/peazipadd.desktop

Maybe there should be a FAQ with this info.

**Comment by catsout** [comment]
I think we can add a install script and do 
`flatpak run --command=install2dolphin io.github.peazip.PeaZip` to put the file to right place.

Do you have any idea?

**Comment by pizzadude** [comment]
Good idea, though I'm not familiar with flatpak packaging.

**Comment by pizzadude** [comment]
Thank you for integrating this @catsout
