### ISSUE TITLE
errors installing io.github.peazip.PeaZip.Addon.i386

### ISSUE THREAD

**Issue by Xathros1** [flathub/io.github.peazip.PeaZip#31]
Hello, when trying to install or update to the newest PeaZip version (8.9.0 from October 9) via flatpak - the Addon mentioned in the title always fails to do and I get the following error message:

>  1. [✗] io.github.peazip.PeaZip.Addon.i386 stable i flathub 11.7 MB / 9.7 MB
> 
> Warning: While trying to apply additional data: The key value file does not have a key "runtime" in the group "Runtime".

and also this one when retrying:

> (flatpak update:14417): GLib-WARNING **: 01:09:45.675: GError set over the top of a previous GError or uninitialized memory.

(Not sure what's going on with the MB, must be a flatpak bug.)

**Comment by catsout** [comment]
What's your flatpak versoin?

**Comment by Xathros1** [comment]
> What's your flatpak versoin?

1.14.0-2.1 on opensuse tumbleweed

**Comment by Zahrun** [comment]
Same problem here with Flatpak 1.12.7 on Kubuntu 22.04

**Comment by Xathros1** [comment]
New error now:

> Warning: While downloading https://downloads.sourceforge.net/project/peazip/Resources/PeaZip%20UNACE%20Plugin/peazip-unace-plugin-linux_3-2_all.deb: server returned status 404
