### ISSUE TITLE
Error running peazip with wayland

### ISSUE THREAD

**Issue by Xathros1** [flathub/io.github.peazip.PeaZip#32]
By clicking one menu entry and then **scrolling over** to another, I get a whole lot of errors and it doesn't happen when you actually click on each the menu entry individually. 
It also looks pretty weird and _detached_ 

![Bildschirmfoto vom 2022-10-15 16-23-14-min](https://user-images.githubusercontent.com/72621668/195991942-52e4d8af-4e4b-4b00-886e-5da33987f27a.png)

> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

it's sometimes also causing a access violation error which actually just force closes the program

> 
> [FORMS.PP] ExceptionOccurred 
>   Sender=EAccessViolation
>   Exception=Access violation
>   Stack trace:
>   $00007F75A414F422
>   $00007F75A414F8AF
>   $00007F75A414FB0D
>   $00007F75A415000E
>   $00007F75B7330158
> 
but I'm not sure that's related

**Comment by catsout** [comment]
You can use `flatseal` to disable the wayland.

**Comment by Xathros1** [comment]
> You can use `flatseal` to disable the wayland.

thanks, that's a workaround

**Comment by peazip** [comment]
I've successfully tested new builds of PeaZip on Wayland on various test machines, I'm replacing X11 for Wayland in the Flatpak version.
