### ISSUE TITLE
Wrong parameter for excluding item(s)

### ISSUE THREAD

**Issue by mbnoimi** [flathub/io.github.peazip.PeaZip#34]
Flatpak version doesn't exclude item(s) because of faulty 7z version (invalid paths)
Example:
```
'/app/peazip/res/bin/7z/7z' a -t7z -m0=Copy -mmt=off -mx0 -ms=off -sccUTF-8 -bb0 -bse0 -bsp2 -w -mtc=on -mta=on '/home/admino/Desktop/Laravel/laravelapp.7z' '/home/admino/Desktop/Laravel/laravelapp'   '-xr0!git' 
```
![image](https://user-images.githubusercontent.com/284547/213894980-47bba158-127c-4fe2-a6ab-5da1683405f6.png)

https://user-images.githubusercontent.com/284547/213895028-f48b712c-187b-45fe-ae64-4dae687a3cb8.mp4

If you noticed in the screenshot 7z's path used in Peazip is totally wrong `/app/peazip/res/bin/7z/7z` even all the links are broken!
There is no `/app` folder in all known Linux system distros.
```
~/.local/share/flatpak/app/io.github.peazip.PeaZip/x86_64/stable/3b6ed67f3980397e459fd8ed871cd83ff90d51ee4339084f7def00daadb89098/files/peazip/res/bin$ tree
.
├── 7z
│   ├── 7z -> /app/bin/7z
│   └── 7zCon.sfx -> /app/bin/7zCon.sfx
├── arc -> /app/Addon/i386/formats/arc
├── brotli
│   └── brotli -> /app/bin/brotli
├── lpaq -> /app/Addon/i386/formats/lpaq
├── paq -> /app/Addon/i386/formats/paq
├── quad -> /app/Addon/i386/formats/quad
├── unace -> /app/Addon/i386/formats/unace
├── upx
│   └── upx -> /app/bin/upx
├── zpaq -> /app/Addon/i386/formats/zpaq
└── zstd
    └── zstd -> /app/bin/zstd

4 directories, 11 files
```

The shipped 7z with flatpak is located in the following path but Peazip doesn't use it instead it uses the broken link(s):

```
~/.local/share/flatpak/app/io.github.peazip.PeaZip/x86_64/stable/3b6ed67f3980397e459fd8ed871cd83ff90d51ee4339084f7def00daadb89098/files/bin$ tree
.
├── 7z
├── 7zCon.sfx
├── brotli
├── install2dolphin
├── peazip
├── unzstd -> zstd
├── upx
├── zstd
├── zstdcat -> zstd
├── zstd-frugal
├── zstdgrep
├── zstdless
└── zstdmt -> zstd

0 directories, 13 files

~/.local/share/flatpak/app/io.github.peazip.PeaZip/x86_64/stable/3b6ed67f3980397e459fd8ed871cd83ff90d51ee4339084f7def00daadb89098/files/bin$ ./7z --help

7-Zip (z) 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15
 64-bit locale=en_US.UTF-8 Threads:8

```

**Comment by catsout** [comment]
> Flatpak version doesn't exclude item(s) because of faulty 7z version (invalid paths)

`-xr0!.git` not work, as `.git` is not the in the root. `-xr0` only exclude `file/dir` in root.  
If I want to exclude `.git` when archiving git dir, I need `-xr0!*/.git` or `-xr!.git`.  
As peazip always uses `-xr0`, so use '*/.git' to exclude.    


> The shipped 7z with flatpak is located in the following path but Peazip doesn't use it instead it uses the broken link(s):

It's wrong, please run `flatpak run --command=sh io.github.peazip.PeaZip`

**Comment by mbnoimi** [comment]
thanks for the clarification.
