### ISSUE TITLE
Linux screenshots

### ISSUE THREAD

**Issue by guihkx** [flathub/io.github.peazip.PeaZip#4]
Hi, I noticed that PeaZip is currently showcasing screenshots of the Windows version, so I took similar screenshots on Ubuntu so you can use them instead (you could store them directly on this repo):

![peazip](https://user-images.githubusercontent.com/626206/115335358-6acc0a80-a173-11eb-9e43-7cabc1589b89.png)

![archive](https://user-images.githubusercontent.com/626206/115335361-6d2e6480-a173-11eb-8922-2da9b3863122.png)

![extract](https://user-images.githubusercontent.com/626206/115335365-6ef82800-a173-11eb-8271-9b13efd9bce9.png)

Cheers.

**Comment by catsout** [comment]
Added.  
Thanks.
