### ISSUE TITLE
Enable socket=wayland by default

### ISSUE THREAD

**Issue by Artim96** [flathub/io.github.peazip.PeaZip#90]
Not sure if that was also an issue with previous versions, but I just installed PeaZip 10.0 as flatpak. At least on Gnome 47, this results in the cursor getting extremely tiny and the UI being badly adapted to the screen size (i.e. the bar on the left in both the default "home screen" view and in settings is uneccessarily narrow). Enabling socket=wayland not only allows the app to be displayed directly through Wayland, but also fixes this issue. And as I don't see a reason why the app shouldn't just natively use Wayland when it supports it. I'd recommend to just enable it as a default. Especially since it has already been requested in #15 3 years ago.

PS: it's not impossible that this off scaling is caused by the experimental Gnome feature "xwayland-native-scaling". So most Gnome users may not experience it yet. But this feature might become the default in the future, and for all I understand it's already part of Plasma 6.x, so it would only make sense to enable this setting before more users experience this issue.

**Comment by peazip** [comment]
I tested first hand Wayland on multiple test machines with current release, building with my build environment.
I'm replacing X11 with Wayland on Flatpak and so far the build seems successful on Flatpak building environment too.
